name: E2E tests - Treasure Hunt App

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  run_e2e_tests:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
      NEXT_PUBLIC_RECAPTCHA_SECRET_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SECRET_KEY }}
      RECAPTCHA_SECRET_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SECRET_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check out backend repo
        uses: actions/checkout@v4
        with:
          repository: UCLL-WorkplaceProject-2025-2026/back-end-team40
          token: ${{ secrets.CHECKOUT_BACKEND_KEY }}
          ref: "dev"
          path: backend

      - name: Build and Run backend
        run: bash ./build_run_backend.sh ./backend

      - name: Build and Run frontend
        run: bash ./build_run_frontend.sh

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install cypress dependencies
        run: npm install

      - name: Run E2E tests
        id: e2e
        run: npm run cypress:run

      - name: Report path
        run: find -name "cucumber-report.html"
